package br.edu.ifg.escolaAprender.frame;

import br.edu.ifg.escolaAprender.util.BancoDeDados;
import br.edu.ifg.escolaAprender.vo.Aluno;
import java.util.List;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author gilberto
 */
public class FrmConsAluno extends javax.swing.JFrame {

    /**
     * Creates new form FrmConsAluno
     */
    public FrmConsAluno() {
        initComponents();
        setLocationRelativeTo(null);
        carregarLista();
    }
    
    public final void carregarLista(){
        TableModel modeloDadosAluno = new AbstractTableModel() {
            private List<Aluno> alunos = BancoDeDados.getAlunos();
            private String[] colunas = new String[]{"Matrícula", "Nome", "Data de Nasc.", "Endereço", "Responsável"};
            
            @Override
            public int getRowCount() {
                return alunos.size();
            }

            @Override
            public int getColumnCount() {
                return 5;
            }
            
            @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Object valorCelula = null;
                    switch(columnIndex) {
                        case 0:
                            valorCelula = alunos.get(rowIndex).getCodigo();
                            break;
                        case 1:
                            valorCelula = alunos.get(rowIndex).getNome();
                            break;
                        case 2:
                            valorCelula = alunos.get(rowIndex).getDataNascimento();
                            break;
                        case 3:
                            valorCelula = alunos.get(rowIndex).getEndereco();
                            break;
                        case 4:
                            valorCelula = alunos.get(rowIndex).getResponsavel();
                            break;
                    }
                    return valorCelula;
                }
                
            @Override
            public String getColumnName(int column) {
                return colunas[column];
            }

        };
        tblConsAluno.setModel(modeloDadosAluno);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsAluno = new javax.swing.JTable();

        setTitle("Consulta de Aluno");

        tblConsAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data Nasc", "Endereço", "Responsavel"
            }
        ));
        tblConsAluno.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tblConsAluno);
        tblConsAluno.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConsAluno;
    // End of variables declaration//GEN-END:variables
}
