/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifg.escolaAprender.frame;

import br.edu.ifg.escolaAprender.util.BancoDeDados;
import br.edu.ifg.escolaAprender.util.FrmContext;
import br.edu.ifg.escolaAprender.vo.Disciplina;
import br.edu.ifg.escolaAprender.vo.Professor;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gilberto
 */
public class FrmCadDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form FrmDisciplina
     */
    public FrmCadDisciplina() {
        initComponents();
        setLocationRelativeTo(null);
        ComboBoxModel boxModel = new DefaultComboBoxModel(BancoDeDados.getProfessores().toArray());
        selecionaProf.setModel(boxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeDisc = new javax.swing.JLabel();
        tfNomeDisc = new javax.swing.JTextField();
        profDisc = new javax.swing.JLabel();
        selecionaProf = new javax.swing.JComboBox();
        semestreDisc = new javax.swing.JLabel();
        campoSemestre = new javax.swing.JTextField();
        anoDisc = new javax.swing.JLabel();
        campoAno = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        inserirAluno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfCodDisc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Disciplina");

        nomeDisc.setText("Nome:");

        profDisc.setText("Professor:");

        selecionaProf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));
        selecionaProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionaProfMouseClicked(evt);
            }
        });
        selecionaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaProfActionPerformed(evt);
            }
        });

        semestreDisc.setText("Semestre:");

        anoDisc.setText("Ano:");

        campoAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoAnoKeyTyped(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.setMaximumSize(new java.awt.Dimension(60, 30));
        salvar.setMinimumSize(new java.awt.Dimension(60, 30));
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        inserirAluno.setText("Inserir Aluno");
        inserirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirAlunoActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        tfCodDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodDiscKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(inserirAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeDisc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeDisc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profDisc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionaProf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anoDisc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(semestreDisc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDisc)
                    .addComponent(tfNomeDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profDisc)
                    .addComponent(selecionaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semestreDisc)
                    .addComponent(campoSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoDisc))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar)
                    .addComponent(inserirAluno))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirAlunoActionPerformed
        FrmContext.showfrmInsAluno();
    }//GEN-LAST:event_inserirAlunoActionPerformed

    private void tfCodDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodDiscKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tfCodDiscKeyTyped

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
                
        Disciplina disc = new Disciplina();
        
        String nome = tfNomeDisc.getText();
        
        Professor prof = (Professor) selecionaProf.getSelectedItem();
        
        disc.setCodigo(Integer.parseInt(tfCodDisc.getText()));
        disc.setNome(tfNomeDisc.getText());
        disc.setProfessor(prof);
        disc.setSemestre(Integer.parseInt(campoSemestre.getText()));
        disc.setAno(Integer.parseInt(campoAno.getText()));
        BancoDeDados.adicionarDisciplinas(disc);
        limparCampos();
        JOptionPane.showMessageDialog(rootPane, nome + " adicionado com sucesso!");
        tfCodDisc.requestFocus();
        
    }//GEN-LAST:event_salvarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        limparCampos();
    }//GEN-LAST:event_limparActionPerformed

    private void campoAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAnoKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_campoAnoKeyTyped

    private void selecionaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaProfActionPerformed
    }//GEN-LAST:event_selecionaProfActionPerformed

    private void selecionaProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionaProfMouseClicked

    }//GEN-LAST:event_selecionaProfMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoDisc;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoSemestre;
    private javax.swing.JButton inserirAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton limpar;
    private javax.swing.JLabel nomeDisc;
    private javax.swing.JLabel profDisc;
    private javax.swing.JButton salvar;
    private javax.swing.JComboBox selecionaProf;
    private javax.swing.JLabel semestreDisc;
    private javax.swing.JTextField tfCodDisc;
    private javax.swing.JTextField tfNomeDisc;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        tfCodDisc.setText("");
        tfNomeDisc.setText("");
        selecionaProf.setSelectedIndex(0);
        campoSemestre.setText("");
        campoAno.setText("");
    }
}
