/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifg.escolaAprender.frame;

import br.edu.ifg.escolaAprender.util.FrmContext;

/**
 *
 * @author gilberto
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        cadAluno = new javax.swing.JMenuItem();
        funcionario = new javax.swing.JMenuItem();
        professor = new javax.swing.JMenuItem();
        disciplina = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        consAluno = new javax.swing.JMenuItem();
        consFunc = new javax.swing.JMenuItem();
        consProf = new javax.swing.JMenuItem();
        consDisc = new javax.swing.JMenuItem();
        opcoes = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);

        Cadastro.setText("Cadastro");

        cadAluno.setText("Aluno");
        cadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoActionPerformed(evt);
            }
        });
        Cadastro.add(cadAluno);

        funcionario.setText("Funcionário");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });
        Cadastro.add(funcionario);

        professor.setText("Professor");
        professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorActionPerformed(evt);
            }
        });
        Cadastro.add(professor);

        disciplina.setText("Disciplina");
        disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinaActionPerformed(evt);
            }
        });
        Cadastro.add(disciplina);

        jMenuBar1.add(Cadastro);

        jMenu3.setText("Consulta");

        consAluno.setText("Aluno");
        consAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consAlunoActionPerformed(evt);
            }
        });
        jMenu3.add(consAluno);

        consFunc.setText("Funcionario");
        consFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consFuncActionPerformed(evt);
            }
        });
        jMenu3.add(consFunc);

        consProf.setText("Professor");
        consProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consProfActionPerformed(evt);
            }
        });
        jMenu3.add(consProf);

        consDisc.setText("Disciplina");
        consDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consDiscActionPerformed(evt);
            }
        });
        jMenu3.add(consDisc);

        jMenuBar1.add(jMenu3);

        opcoes.setText("Opções");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        opcoes.add(sair);

        jMenuBar1.add(opcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        FrmContext.showfrmCadFunc();
    }//GEN-LAST:event_funcionarioActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void cadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoActionPerformed
        FrmContext.showFrmCadAluno();
    }//GEN-LAST:event_cadAlunoActionPerformed

    private void professorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorActionPerformed
        FrmContext.showfrmCadProf();
    }//GEN-LAST:event_professorActionPerformed

    private void disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaActionPerformed
        FrmContext.showfrmCadDisc();
    }//GEN-LAST:event_disciplinaActionPerformed

    private void consAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consAlunoActionPerformed
        FrmContext.showfrmConsAluno();
    }//GEN-LAST:event_consAlunoActionPerformed

    private void consFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consFuncActionPerformed
        FrmContext.showfrmConsFunc();
    }//GEN-LAST:event_consFuncActionPerformed

    private void consProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consProfActionPerformed
        FrmContext.showfrmConsProf();
    }//GEN-LAST:event_consProfActionPerformed

    private void consDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consDiscActionPerformed
        FrmContext.showfrmConsDisc();
    }//GEN-LAST:event_consDiscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem cadAluno;
    private javax.swing.JMenuItem consAluno;
    private javax.swing.JMenuItem consDisc;
    private javax.swing.JMenuItem consFunc;
    private javax.swing.JMenuItem consProf;
    private javax.swing.JMenuItem disciplina;
    private javax.swing.JMenuItem funcionario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu opcoes;
    private javax.swing.JMenuItem professor;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables
}
